language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: Z63n/6bIIYK0DODGlo/705ce95Nht4Gjqx+gAmOqacTOcjlCdiM/s7fd8VKNOl53kWBw3ey1hk4QqNQDPrEedFvwNNYn6vxCqywvrbmIfAHV+OxHKNPY5mIalYK44TRt+fBBJz7uzWxZzrf2HaoZ/PLgchbl34llXWNd9uk35uWRLNCTEAQtK2Ki3ice/fkgOWXrUzdwkhXW76gV3cfvLII8NIDzdBuhKz+3niKNc6gd7QFbnt2edK3W36OcFgBINhoE8Tre5+B9kzech5ZwnCRYdyWWvQy/1RT4aZicx6411B1zw3oWId+aSi4IVBMrpejPMmh3ItKcZJD0HHvtg3ws0rRNWZfj0eQ17OoRpYDtjOB/VOmIcpRAKo2d1WBPe4Xo+/YAq9gDHAClhx9jdcN+Ip2YWlKHZGU2ao8bQ99fLZ9NlrQBXpUNtMQ2a+Y3G4BU2GqQFNBW4kd28l0XGBTblLxIeCPAN1Tem/5COaE/SgYDDJeQePpdJaglh1tB8HIQc+jAO+x4Cg0F/YQDpcWCYBoFaauY1+i8VcDJKbWUrUzFq51wH4qceWA0ft8krFaCtNDJJAX5zcP+8b59u/2fz7A3PTbiDBfjwWyWL5j88BrSu82/+PI82fHzfcgdtpQMSGMl68Zbibrh4xGitNYk9uJ7YZmP5gdZpcfO0uw=
    on:
      branch: master
      tags: true